
baseurl: /front-end-findings
title:            Front End Findings
description:      A jekyll theme. Because I scribble.
url:              # Site url.
signoff:          # Your name.
disqus_shortname: frontendfindings
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-47859092-1

links:
  # - name:         About
  #   url:          /about
  # - name:         Contribute
  #   url:          /contribute
  # - name:         Blog
  #   url:          http://muan.co
  #   external:     true
  # - name:         Email
  #   url:          mailto:hello@muan.co
  #   external:     true
  # - name:         GitHub
  #   url:          http://github.com/muan
  #   external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart